In [9]:
import numpy as np
np.__version__

'2.4.0'

import numpy as np
print("NumPy version:", np.__version__)


In [10]:
import numpy as np
print("NumPy version:", np.__version__)


NumPy version: 2.4.0


In [11]:
print("Hello, World!")

Hello, World!


## Advance Numpy Methods ##

"""
objective:
Multidimentional numpy
Numpy Operation
Numpy Axis
Numpy Random
"""

"""
Multidimension Numpy Arrays
mathematical objects:
scaler(OD),vector(1D),Matrix(2D),Tensor(xD where x>2)
"""

In [12]:
import numpy as np

scaler = np.array(69)
vector = np.array([1, 2, 3])
matrix = np.array(
    [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]
)


In [13]:
print('Scaler:', scaler)
print('Dimension of scaler:',scaler.ndim)

Scaler: 69
Dimension of scaler: 0


In [14]:
print('vetor' , vector)
print('dimension od vector:', vector.ndim)

vetor [1 2 3]
dimension od vector: 1


In [15]:
print('matrix:\n', matrix)
print('dimension of matrix:', matrix.ndim)

matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
dimension of matrix: 2


In [16]:
tensor = np.array(
    [[[[1, 2],[4,5]]]]
)
tensor.ndim


4

## numpy indexing
##



In [17]:
myarrau = np.array (
    [[[1,2],
      [3,4]]]
)
shape = myarrau.shape
print(shape)


(1, 2, 2)


In [18]:
array_1d = np.array([1, 2, 3, 4, 5])
print(array_1d[2])
print(array_1d[-1])

3
5


In [19]:
array_2d = np.array(
    [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]
)   
print(array_2d[1, 2])
print(array_2d[-1,-2])

6
8


In [22]:
array_3d = np.array(
    [
      [
         [1, 2, 3, 4],
         [5, 6, 7, 8],
         [9, 10,11,12]
      ],

     [
         [13,14,15,16],
         [17,18,19,20],
         [21,22,23,24]
     ],

     [
         [25,26,27,28],
         [29,30,31,32],
         [33,34,35,36]
      ]
    ]
  )
print(array_3d[1,2,0])
print(array_3d[-1,-2,-4])
shape = array_3d.shape
print(shape)

21
29
(3, 3, 4)
