In [1]:
import numpy as np
np.__version__

'2.4.0'

import numpy as np
print("NumPy version:", np.__version__)


In [2]:
import numpy as np
print("NumPy version:", np.__version__)


NumPy version: 2.4.0


In [3]:
print("Hello, World!")

Hello, World!


## Advance Numpy Methods ##

"""
objective:
Multidimentional numpy
Numpy Operation
Numpy Axis
Numpy Random
"""

"""
Multidimension Numpy Arrays
mathematical objects:
scaler(OD),vector(1D),Matrix(2D),Tensor(xD where x>2)
"""

In [4]:
import numpy as np

scaler = np.array(69)
vector = np.array([1, 2, 3])
matrix = np.array(
    [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]
)


In [5]:
print('Scaler:', scaler)
print('Dimension of scaler:',scaler.ndim)

Scaler: 69
Dimension of scaler: 0


In [6]:
print('vetor' , vector)
print('dimension od vector:', vector.ndim)

vetor [1 2 3]
dimension od vector: 1


In [7]:
print('matrix:\n', matrix)
print('dimension of matrix:', matrix.ndim)

matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
dimension of matrix: 2


In [8]:
tensor = np.array(
    [[[[1, 2],[4,5]]]]
)
tensor.ndim


4

## numpy indexing
##



In [9]:
myarrau = np.array (
    [[[1,2],
      [3,4]]]
)
shape = myarrau.shape
print(shape)


(1, 2, 2)


In [10]:
array_1d = np.array([1, 2, 3, 4, 5])
print(array_1d[2])
print(array_1d[-1])

3
5


In [11]:
array_2d = np.array(
    [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]
)   
print(array_2d[1, 2])
print(array_2d[-1,-2])

6
8


In [12]:
array_3d = np.array(
    [
      [
         [1, 2, 3, 4],
         [5, 6, 7, 8],
         [9, 10,11,12]
      ],

     [
         [13,14,15,16],
         [17,18,19,20],
         [21,22,23,24]
     ],

     [
         [25,26,27,28],
         [29,30,31,32],
         [33,34,35,36]
      ]
    ]
  )
print(array_3d[1,2,0])
print(array_3d[-1,-2,-4])
shape = array_3d.shape
print(shape)

21
29
(3, 3, 4)


In [13]:
"""
Numpy slicing
-array[start:stop:step]
-default start = 0
-default stop = size of dimension
-end index is not included
"""

print("Slicing examples:")
print(array_1d)
print('slicing')
print(array_1d[1:4])

print("Now 2D array slicing")

print("Matrix\n", array_2d)
print(array_2d[0:2, 1:3])


Slicing examples:
[1 2 3 4 5]
slicing
[2 3 4]
Now 2D array slicing
Matrix
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 3]
 [5 6]]


In [14]:
my_2D_array = np.array(
    [[10, 20, 30, 40, 50],
     [60, 70, 80, 90, 100],
     [110,120,130,140,150],
     [160,170,180,190,200],
     [210,220,230,240,250  ]]
)
print ("my 2d Matrix\n", my_2D_array)
print("slicing\n" , my_2D_array[1:4, 2:5])

my 2d Matrix
 [[ 10  20  30  40  50]
 [ 60  70  80  90 100]
 [110 120 130 140 150]
 [160 170 180 190 200]
 [210 220 230 240 250]]
slicing
 [[ 80  90 100]
 [130 140 150]
 [180 190 200]]


In [15]:
"""
 Numpy reshape : changing the shape of an array without changing its data.
condition: the total number of elements must remain the same.
my_array = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print("Original array:\n", my_array)
reshaped_array = my_array.reshape((3,4))
"""

'\n Numpy reshape : changing the shape of an array without changing its data.\ncondition: the total number of elements must remain the same.\nmy_array = np.array([1,2,3,4,5,6,7,8,9,10,11,12])\nprint("Original array:\n", my_array)\nreshaped_array = my_array.reshape((3,4))\n'

In [16]:
my_2D_array.shape
reshaped_array = my_2D_array.reshape((5,5))


### Numpy Filterling ###

In [17]:
'''
selcted elements from array
'''
my_1D_array = np.array(
    [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
)
filer_mask = [True, False, True, False, True, False, True, False, True, False]
filer_array = my_1D_array[filer_mask]
print(filer_array)

indices = [0, 2, 4, 6, 8]
filer_array2 = my_1D_array[indices]
print(filer_array2) 

[10 30 50 70 90]
[10 30 50 70 90]


## Vectorization ###

In [18]:
# here we can mod all elements of array in one time without loop
my_1D_array
my_1D_array = my_1D_array % 2
print(my_1D_array)

[0 0 0 0 0 0 0 0 0 0]


# Broadcasting
#

In [19]:
''' 
-converting a lower shape into higher shape
-conditon: require that the array involved in the operation either have the same size
in each dimension or that ine of the arrays has size 1 in the dimension being broadcasted.
'''




' \n-converting a lower shape into higher shape\n-conditon: require that the array involved in the operation either have the same size\nin each dimension or that ine of the arrays has size 1 in the dimension being broadcasted.\n'

In [20]:
my_1D_array.ndim

1